### ISSUE TITLE
Handle Error for fmt.Fprintln()

### ISSUE THREAD

**Issue by jyono** [ServiceWeaver/workshops#41]
https://github.com/ServiceWeaver/workshops/blob/main/04/main.go#L69

for example 04 and beyond, 

```
	fmt.Fprintln(w, string(bytes))
```

to 

```
	_, err = fmt.Fprintln(w, string(bytes))
	if err != nil {
		return
	}
```

**Comment by mwhittaker** [comment]
Hi @jyono! I might be misunderstanding something, but it seems like the two snippets you posted behave identically?

**Comment by jyono** [comment]
@mwhittaker i'm just saying that its probably preferred to explicitly handle the error since that method can return one. it might confuse a user if their log doesn't appear because of an internal error and continues execution? probably not that serious :D

**Comment by mwhittaker** [comment]
Ah, I see. I opened #42 to address this.
